### ISSUE TITLE
java.lang.ClassNotFoundException: delight.nashornsandbox.internal.InterruptTest when using as external JAR

### ISSUE THREAD

**Issue by Jachdich** [javadelight/delight-nashorn-sandbox#100]
I need to use this library as an external JAR for my project however whenever I try to run any JS it always gives the error:

```
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:508) [spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1579) [spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1517) [spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoClassDefFoundError: delight/nashornsandbox/NashornSandboxes
	at com.cospox.relay.ChatFunctions.processChatMessage(ChatFunctions.java:47) ~[?:?]
	at com.cospox.relay.Main.onPlayerChat(Main.java:56) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1.jar:git-Spigot-492a779-731e819]
	... 11 more

```

I have added the JAR to my MANIFEST.MF like so:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.5
Created-By: 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10 (Private Build)
Class-Path: ./libs/JDA.jar ./libs/NashornSandbox.jar
```

and ./libs/NashornSandbox.jar is there. I'm not really sure whether this is an issue with my code or nashorn-sandbox, but any help would be much appriciated either way as google is not helping me.

**Comment by mxro** [comment]
Hi @Jachdich, thank you for your question!

To me it looks like it doesn't load the files from the NashornSanbox.jar at all. `NashornSandboxes` is the entry class and it cannot find it. 

```
Caused by: java.lang.NoClassDefFoundError: delight/nashornsandbox/NashornSandboxes
``` 

Could you unzip your jar file and see if all classes are in the jar? You will also need the dependencies in the same jar file.

An earlier version has been releases as bundled jar: https://github.com/javadelight/delight-nashorn-sandbox/releases - you can download that and check it against the jar you have created.

**Comment by Jachdich** [comment]
Hmm... Of course the JARs are the same because I didn't modify it at all. I'm trying to load the JAR as an external library on the classpath. 

However, it is getting loaded mostly because if I remove `sandbox.setMaxCPUTime(100);` and `sandbox.setExecutor(Executors.newSingleThreadExecutor());` from my code then it executes correctly. It seems to either be a problem with how I'm loading the jar or a problem with the `delight.nashornsandbox.internal.InterruptTest` class. Any thoughts?

**Comment by mxro** [comment]
Hi @Jachdich , maybe you could upload the JAR you have created and link it here?

Did you try commenting in the maven-assembly plugin and building the JAR with that: https://github.com/javadelight/delight-nashorn-sandbox/blob/master/pom.xml#L98

**Comment by Jachdich** [comment]
Thanks for the response! I've actually been meaning to make a GitHub for the project so I can link you that when I create it (probably tomorrow) and I'll include the jar. 

I've not actually used maven before so I will look into that. Thanks!

**Comment by Jachdich** [comment]
Any update on this @mxro ?

**Comment by mxro** [comment]
@Jachdich As per my comment above, did you try it with the maven-assembly-plugin?

> Did you try commenting in the maven-assembly plugin and building the JAR with that: https://github.com/javadelight/delight-nashorn-sandbox/blob/master/pom.xml#L98

**Comment by Jachdich** [comment]
@mxro Oh I forgot to say: I never managed to get it working because I've never used Maven before and the tutorials online are rather confusing. If you know of a good tutorial then that would be much apriciated.

**Comment by mxro** [comment]
@Jachdich What about the official Maven docs? http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html 

For a more in depth view there is also 'Maven: The Definitive Guide' published by O'Reilly

**Comment by mxro** [comment]
Closing old issues - please be welcome to reopen or raise a new one.
