### ISSUE TITLE
importClass is not defined

### ISSUE THREAD

**Issue by fengchichenmo** [javadelight/delight-nashorn-sandbox#78]
When I use this sandbox,  **load mozilla_compat.js**， and use **importClass** to import java class, it tells me **"importClass" is not defined**.
there is code:
```java
        NashornSandbox sandbox = NashornSandboxes.create();
        sandbox.setMaxCPUTime(1000*30);
        sandbox.setMaxMemory(50*1024*1024);
        sandbox.allowNoBraces(false);
        sandbox.setMaxPreparedStatements(30); // because preparing scripts for execution is expensive
        sandbox.setExecutor(Executors.newSingleThreadExecutor());
        String loadJS ="load('nashorn:mozilla_compat.js'); importClass(java.lang.String);";
        String loadClass = "; ";
        String funcJs = loadJS + loadClass+ "function execute(data){  var o={}, i=0; while (true) {o[i++]='abc';} return JSON.stringify(o);}";
        sandbox.eval(funcJs);
```

there is error:
Exception in thread "main" javax.script.ScriptException: ReferenceError: "importClass" is not defined in <eval> at line number 3
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
	at delight.nashornsandbox.internal.JsEvaluator.run(JsEvaluator.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: <eval>:3 ReferenceError: "importClass" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:278)
	at jdk.nashorn.internal.runtime.ScriptObject.noSuchProperty(ScriptObject.java:2357)
	at jdk.nashorn.internal.runtime.ScriptObject.noSuchMethod(ScriptObject.java:2283)
	at jdk.nashorn.internal.runtime.ScriptObject.findGetMethod(ScriptObject.java:1954)
	at jdk.nashorn.internal.objects.Global.findGetMethod(Global.java:2170)
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1820)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$76$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 9 more

i don't know why, is there anyone can help?

**Comment by mxro** [comment]
Not really sure what is the issue here? Do you need rhino compatibility?

**Comment by fengchichenmo** [comment]
I mean when use jdk8 Nashorn direct, it is ok. But when I use NashornSandbox , it tell me **"importClass is not defined"**

```java
NashornScriptEngineFactory factory = new NashornScriptEngineFactory();
        ScriptEngine scriptEngine = factory.getScriptEngine();
        String loadJS ="load('nashorn:mozilla_compat.js'); importClass(java.lang.String);";
        String loadClass = "; ";
        String funcJs = loadJS + loadClass+ "function execute(data){  var o={}, i=0; while (i<2) {o[i++]='abc';} return JSON.stringify(o);}";
        try {
            scriptEngine.eval(funcJs);
            Invocable inv = (Invocable) scriptEngine;
            System.out.println(inv.invokeFunction("execute","afa"));
        } catch (ScriptException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
        System.out.println("end2");
```

and this is result:

```text
{"0":"abc","1":"abc"}
end2
```

What does NashornSandbox  do to result this error?
@mxro

**Comment by mxro** [comment]
Sorry not so sure why this error comes up here. There might be some code in mozilla_compat.js which is prevented from loading correctly by the sandbox.

Might be that `Object.defineProperty(this, ,,,` is prevented from running. Could you test if Object.defineProperty would work in the script directly?

Also you could try to load this code directly into the sandbox and see if there are any errors.

http://cr.openjdk.java.net/~sundar/8010924/webrev.00/src/jdk/nashorn/internal/runtime/resources/mozilla_compat.js.html

**Comment by fengchichenmo** [comment]
@mxro  Thank you, I test Object.defineProperty directly, it work. There is my test code:

```java
        NashornSandbox sandbox = NashornSandboxes.create();
        sandbox.setMaxCPUTime(1000*30);
        sandbox.setMaxMemory(50*1024*1024);
        sandbox.allowNoBraces(false);
        sandbox.setMaxPreparedStatements(30); // because preparing scripts for execution is expensive
        sandbox.setExecutor(Executors.newSingleThreadExecutor());
		String defineStr = "Object.defineProperty(this, \"importClass\", {\n" +
                "    configurable: true, enumerable: false, writable: true,\n" +
                "    value: function(clazz) {\n" +
                "        if (Java.isType(clazz)) {\n" +
                "            var className = Java.typeName(clazz);\n" +
                "            var simpleName = className.substring(className.lastIndexOf('.') + 1);\n" +
                "            this[simpleName] = clazz;\n" +
                "        } else {\n" +
                "            throw new TypeError(clazz + \" is not a Java class\");\n" +
                "        }\n" +
                "    }\n" +
                "});";
        sandbox.allow(String.class);
        String loadJS =" importClass(java.lang.String);";
        String loadClass = "; ";
        String funcJs = defineStr +loadJS + loadClass+ "function execute(data){ var str=new String('defineProprety'); var o={}, i=0; while (i<2) {o[i++]='abc';} return JSON.stringify(o)+str;}";
        sandbox.eval(funcJs);
        Invocable inv = sandbox.getSandboxedInvocable();
        Object res = null;
        try {
            res = inv.invokeFunction("execute","afa");
        } catch (ScriptException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
        System.out.println(res);
```

result is:
```txt
{"0":"abc","1":"abc"}defineProprety
end
```

But i still don't understand why  **load('nashorn:mozilla_compat.js')** is not work. Is there any idea to load the entire nashorn:mozilla_compat.js file?

**Comment by fengchichenmo** [comment]
@mxro  I figure out, should set allowLoadFunctions to true, will make load('nashorn:mozilla_compat.js')

```java
sandbox.allowLoadFunctions(true);
```

Is it reasonable for allowLoadFunctions makes load js file not work?

**Comment by mxro** [comment]
@fengchichenmo That's great you got it sorted out.

Yes, I think it's quite reasonable that the load function does not work when load functions are not explicitly enabled!

**Comment by mxro** [comment]
Closing old issues - please be welcome to reopen or raise a new one.
