### ISSUE TITLE
Sanitizer create not valid "for"?

### ISSUE THREAD

**Issue by mikcorer** [javadelight/delight-nashorn-sandbox#81]
I try eval one library, but I get this error. I think that sanitizer not must insert `__if()` after for loop condition. 

`Exception in thread "main" javax.script.ScriptException: <eval>:125:28 Expected ) but found ;
    for (o = c; o < u;__if(); o++) a = [], t[o] = a, e(a, r, f, i)
                            ^ in <eval> at line number 125 at column number 28`

**Comment by mxro** [comment]
Hi There! Thank you for submitting this issue. Could you provide the original code of the library before sanitisation?

**Comment by mikcorer** [comment]
I tried to eval webpacked library mathjs. I found line (2485) and add my for `for (var test = 0; test < 10; test++) {}`. In native ScriptEngine this file work fine. 
[_mathjs.zip](https://github.com/javadelight/delight-nashorn-sandbox/files/3002131/_mathjs.zip)

**Comment by mxro** [comment]
Does it have the same issue for non webpacked mathjs. Maybe that might be a workaround?

**Comment by mikcorer** [comment]
Mathjs is a library for nodejs, so you have to use a webpack and get around hardly. The same problem is present if other libraries are used. Maybe, it is not the best idea to use fat libraries for Nashorn Sandbox, but now there is a need. I review and test different approaches for scripting and in the use of Nashorn Sandbox faced such a problem.

**Comment by mxro** [comment]
Could you try this again with the new version released today?

**Comment by mikcorer** [comment]
Tested, but the error remained.

**Comment by KevinRoebert** [comment]
Hi. I've a similar problem. In native ScriptEngine everthing works fine.

I try to minify uploaded JS first before storing on the machine. Therefor I use [UglifyJS3](https://github.com/mishoo/UglifyJS2). You can build an UglifyJS3 by yourself with npm and the `uglifyjs --self -c -m -o /tmp/uglifyjs.js` command or you can use the attached **uglifyjs.js** file in the uploaded zip. In the zip is also a small script that use UglifyJS3 to convert a string in a minified version.
[resources.zip](https://github.com/javadelight/delight-nashorn-sandbox/files/3094610/resources.zip)

**Tested with version 0.1.22.**
The Java-Code looks like this:

```java
public class Minifier {
    ScriptEngine engine;
    Invocable invoke;

    public Minifier() throws ScriptException {
        NashornSandbox sandbox = NashornSandboxes.create();
        sandbox.disallowAllClasses();
        sandbox.setMaxCPUTime(30000);
        sandbox.setMaxMemory(50 * 1024);
        sandbox.allowNoBraces(true);
        sandbox.setMaxPreparedStatements(30);
        sandbox.setExecutor(Executors.newSingleThreadExecutor());

        sandbox.eval(getScript("/uglifyjs.js"));
        sandbox.eval(getScript("/minify.js"));

        invoke = (Invocable) engine;
    }

    public String minify(String sourceCode) throws ScriptException, NoSuchMethodException {
        return (String) invoke.invokeFunction("minifyCode", sourceCode);
    }

    private String getScript(String name) {
        BufferedReader bir = new BufferedReader(new InputStreamReader(getClass().getResourceAsStream(name)));
        StringBuilder sb = new StringBuilder();

        try {
            String line;

            while ((line = bir.readLine()) != null) {
                sb.append(line).append("\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return sb.toString();
    }
}

```

Now I get the following exception:
```java
javax.script.ScriptException: <eval>:153:63 Expected ) but found ;
  for (var n, t = e.parent(-1), i = 0; n = e.parent(i++);__if(); t = n) {__if();
                                                               ^ in <eval> at line number 153 at column number 63
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
	at delight.nashornsandbox.internal.JsEvaluator.run(JsEvaluator.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:153:63 Expected ) but found ;
  for (var n, t = e.parent(-1), i = 0; n = e.parent(i++);__if(); t = n) {__if();
                                                               ^
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
	at jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:350)
	at jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:337)
	at jdk.nashorn.internal.parser.Parser.forStatement(Parser.java:1322)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:893)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.functionBody(Parser.java:2901)
	at jdk.nashorn.internal.parser.Parser.functionExpression(Parser.java:2663)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:875)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.functionBody(Parser.java:2901)
	at jdk.nashorn.internal.parser.Parser.functionExpression(Parser.java:2663)
	at jdk.nashorn.internal.parser.Parser.memberExpression(Parser.java:2506)
	at jdk.nashorn.internal.parser.Parser.leftHandSideExpression(Parser.java:2372)
	at jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:3147)
	at jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:3114)
	at jdk.nashorn.internal.parser.Parser.expression(Parser.java:3282)
	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1150)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
	... 9 more
```

**Comment by mxro** [comment]
My guess would be that this has to do with the 'poison pill' statement inserted and the regex used to do so.

https://github.com/foxep2001/delight-nashorn-sandbox/blob/master/src/main/java/delight/nashornsandbox/internal/JsSanitizer.java#L73

Does tuning these regexes help with the issues?

**Comment by mxro** [comment]
Closing old issues - please be welcome to reopen or raise a new one.
