### ISSUE TITLE
NashornSandbox.setMaxCPUTime() NOT always work when evaluating script includes infinite loop

### ISSUE THREAD

**Issue by wangkaish** [javadelight/delight-nashorn-sandbox#99]
I `setMaxCPUTime(60)` method and then `eval()` a script includes an infinite loop.

```java
    static volatile Thread t1;

    public static void main(String[] args) throws Exception {
        StringBuilder js = new StringBuilder();
        js.append("var System = Java.type(\"java.lang.System\");\n");
        js.append("for(;;){\n");
        js.append("    System.out.println(\"....................outer\");\n");
        js.append("    try{\n");
        js.append("        for(;;){}\n");
        js.append("    }catch(e){\n");
        js.append("        System.out.println(e);\n");
        js.append("    }finally{\n");
        js.append("        System.out.println(\"finally unlock.... \");\n");
        js.append("    }\n");
        js.append("}");
        System.out.println(js);
        System.out.println("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
        System.out.println();
        ExecutorService executorService = Executors.newSingleThreadExecutor(r -> {
            t1 = new Thread(r);
            return t1;
        });
        NashornSandbox sandbox = NashornSandboxes.create();
        sandbox.allow(System.class);
        sandbox.setMaxCPUTime(60);
        sandbox.setMaxMemory(1024 * 1024 * 1024 * 8);
        sandbox.allowNoBraces(false);
        sandbox.setMaxPreparedStatements(30); // because preparing scripts for execution is expensive
        sandbox.setExecutor(executorService);
        try {
            sandbox.eval(js.toString());
        } catch (Throwable e) {
            e.printStackTrace();
        }
        for (; ; ) {
            Thread.sleep(2000);
            System.out.println("t1 state: " + t1.getState());
        }
    }
```

I am expecting the thread will be stopped when it consumes over 60 CPU time.  But it doesn't always work.

Sometimes I got the expected result:
```
....................outer
java.lang.InterruptedException
finally unlock.... 
....................outer
2020-01-07 14:52:52.728 [ERROR] NashornSandbox - ThreadMonitor: Thread hard shutdown!
java.lang.ThreadDeath
finally unlock.... 
delight.nashornsandbox.exceptions.ScriptCPUAbuseException: Script used more than the allowed [60 ms] of CPU time. The operation could NOT be gracefully interrupted.
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:251)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:225)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:193)
	at com.test.TestJsSandboxGithub.main(TestJsSandboxGithub.java:64)
t1 state: WAITING
t1 state: WAITING
t1 state: WAITING
```

But sometimes I got the unexpected result:
```
....................outer
java.lang.InterruptedException
finally unlock.... 
....................outer
2020-01-07 14:43:46.784 [ERROR] NashornSandbox - ThreadMonitor: Thread hard shutdown!
java.lang.ThreadDeath
finally unlock.... 
....................outer
delight.nashornsandbox.exceptions.ScriptCPUAbuseException: Script used more than the allowed [60 ms] of CPU time. The operation could NOT be gracefully interrupted.
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:251)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:225)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:193)
	at com.test.TestJsSandboxGithub.main(TestJsSandboxGithub.java:64)
t1 state: RUNNABLE
t1 state: RUNNABLE
t1 state: RUNNABLE
t1 state: RUNNABLE
```

**Comment by wangkaish** [comment]
The js not stop log: 
```log
....................outer
java.lang.InterruptedException
finally unlock.... 
....................outer
2020-01-07 14:43:46.784 [ERROR] NashornSandbox - ThreadMonitor: Thread hard shutdown!
java.lang.ThreadDeath
finally unlock.... 
....................outer
delight.nashornsandbox.exceptions.ScriptCPUAbuseException: Script used more than the allowed [60 ms] of CPU time. The operation could NOT be gracefully interrupted.
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:251)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:225)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:193)
	at com.test.TestJsSandboxGithub.main(TestJsSandboxGithub.java:64)
t1 state: RUNNABLE
t1 state: RUNNABLE
t1 state: RUNNABLE
t1 state: RUNNABLE
```

**Comment by wangkaish** [comment]
The js stoped log: 
```log
....................outer
java.lang.InterruptedException
finally unlock.... 
....................outer
2020-01-07 14:52:52.728 [ERROR] NashornSandbox - ThreadMonitor: Thread hard shutdown!
java.lang.ThreadDeath
finally unlock.... 
delight.nashornsandbox.exceptions.ScriptCPUAbuseException: Script used more than the allowed [60 ms] of CPU time. The operation could NOT be gracefully interrupted.
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:251)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:225)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:193)
	at com.test.TestJsSandboxGithub.main(TestJsSandboxGithub.java:64)
t1 state: WAITING
t1 state: WAITING
t1 state: WAITING
```

**Comment by mxro** [comment]
@wangkaish Thank you for submitting this issue!

I think this might not be an issue with the sandbox but rather with the single thread executor service 

`ExecutorService executorService = Executors.newSingleThreadExecutor(r -> {`

As far as I understand it, the executor service might leave the thread running, even if nothing is currently executed (as is the case here, since the running execution would stop after the exception is thrown). 

Try shutting down the executor service after the exception is thrown:

```
executorService.shutdown();
```

And then check if the thread is still running.

Hope this answers your question!

**Comment by wangkaish** [comment]
@mxro Thanks for your explain.
